// GENERATED by scripts/vendor-vehicle-meshes.mjs — do not edit by hand.
//
// The recovered vehicles, converted from the decoded `src/legacy/cars-catalog.json` into the
// `graphysx-mesh-json` payload a v2 `model` entity loads. Each entry carries its archive
// source path and SHA-256 so a scene referencing it keeps its lineage (PRODUCT_SPEC §11).
//
// These are referenced by URL rather than by catalog id: `src/agent-world-asset-catalog.ts`
// is generated from `public/assets/**` by `scripts/build-asset-catalog.mjs` and is a shared
// file. Registering them there is a one-line follow-up — see the report — after which
// `asset: { id: "archive-impreza" }` works too and they become discoverable via `api.assets()`.

export type ArchiveVehicleRecord = {
  readonly id: string;
  readonly label: string;
  readonly url: string;
  /** Longest native span, in archive units. Passing it as `fitSize` reproduces archive scale 1:1. */
  readonly nativeFitSize: number;
  readonly bounds: { readonly min: readonly number[]; readonly max: readonly number[]; readonly size: readonly number[] };
  readonly meshCount: number;
  readonly triangles: number;
  readonly source: string;
  readonly sha256: string;
  /** FAITHFUL / INFERRED / PARTIAL / DELIBERATELY ABSENT, verbatim from the vendoring step. */
  readonly notes: readonly string[];
};

export const ARCHIVE_VEHICLE_MESHES: readonly ArchiveVehicleRecord[] = [
  {
    "id": "archive-impreza",
    "url": "/assets/vehicles/archive-impreza.json",
    "label": "Subaru Impreza (archive)",
    "nativeFitSize": 4.782,
    "bounds": {
      "min": [
        -1.02,
        -0.828,
        -2.391
      ],
      "max": [
        1.017,
        0.666,
        2.391
      ],
      "size": [
        2.037,
        1.494,
        4.782
      ]
    },
    "meshCount": 5,
    "triangles": 5207,
    "source": "Yanik C++ BCKUP/Media/Models/cars/impreza.3ds",
    "sha256": "87b3890636c2f6849e0c714e8ccec0913140bbc237899b89e8db0e788fb03091",
    "notes": [
      "FAITHFUL: vertex/index/UV arrays verbatim from the decoded 3DS; the three chassis material slots and their face assignments; the four wheel hub offsets.",
      "FAITHFUL: textures are the archive's own, vendored under /assets/textures/cars (ChassisSTi/Windows/Undercarriage/Wheel .bmp). The catalog records the original names CHASIS.JPG / VENTANAS.JPG / CHASIS_A.JPG / RUEDAS.JPG; the shipped BMPs are those same maps under the workshop's vendored names.",
      "INFERRED: specular power per slot (the 3DS shininess was not carried into the catalog).",
      "DELIBERATELY ABSENT: wheels are baked into the model at their catalog offsets and do not steer or spin. A model entity is one static mesh group; articulation belongs to a rig the platform does not have yet."
    ]
  },
  {
    "id": "archive-cobra",
    "url": "/assets/vehicles/archive-cobra.json",
    "label": "Low Cobra (archive)",
    "nativeFitSize": 4.841,
    "bounds": {
      "min": [
        -1.261,
        -0.989,
        -2.42
      ],
      "max": [
        1.261,
        0.806,
        2.421
      ],
      "size": [
        2.522,
        1.795,
        4.841
      ]
    },
    "meshCount": 5,
    "triangles": 3266,
    "source": "Yanik C++ BCKUP/Media/Models/cars/Low_Cobra.3DS",
    "sha256": "1af174e5f135a530e833fafcaadcef604abbaa159c1d07c2cd189adda40688f6",
    "notes": [
      "FAITHFUL: vertex/index/UV arrays and the four tire hub offsets, as decoded.",
      "INFERRED, upstream of this repo: the decoder rotated the source (authored ~200 units along X) onto Z and scaled it by 0.024 to sit at Impreza size. That normalisation is the workshop's, recorded in convert-cars.mjs, not the archive's own transform.",
      "PARTIAL: the 3DS records four material names ('2 - Default', '19 - Default', '20 - Default', '8 - Default') with no texture bindings carried into the catalog, so the whole body takes one livery — the same choice race-scene.ts makes. The glass is therefore painted with the body map rather than being separately transparent.",
      "DELIBERATELY ABSENT: tire textures (TA_Tire.tga / Tire_trd.tga are workshop-only) and wheel articulation."
    ]
  },
  {
    "id": "archive-piste-ovale",
    "url": "/assets/vehicles/archive-piste-ovale.json",
    "label": "Piste Ovale (archive)",
    "nativeFitSize": 200,
    "bounds": {
      "min": [
        -75,
        0,
        -100
      ],
      "max": [
        75,
        19.391,
        100
      ],
      "size": [
        150,
        19.391,
        200
      ]
    },
    "meshCount": 1,
    "triangles": 236,
    "source": "AtmelCubx/PisteOvale.tvm",
    "sha256": "88d83fce3dff562cba9211692020629c08caf4356cb98318bb01de51dca70113",
    "notes": [
      "FAITHFUL: the decoded TVM vertex/index arrays and the native 150 x 19.4 x 200 extent.",
      "PARTIAL: the TVM holds several material groups but the decoder does not preserve their assignments, so this ships as one untextured slab. race-scene.ts papered over that by projecting a concrete texture per face; a gallery piece should not invent a surface the record does not have, so it stays flat grey and says so.",
      "ARCHIVE FINDING (workshop RECUPERATION_LEDGER.md): PisteOvale was never wired into CarScene. The 2008 car drove on heightmap terrain; the oval is an unused asset."
    ]
  }
] as const;

export function archiveVehicleMesh(id: string): ArchiveVehicleRecord {
  const record = ARCHIVE_VEHICLE_MESHES.find((candidate) => candidate.id === id);
  if (!record) throw new Error(`Unknown archive vehicle mesh: ${id}`);
  return record;
}
